name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Setup qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build push
        uses: docker/build-push-action@v2
        env:
          DN_DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        with:
          context: .
          file: Dockerfile
          push: false
          tags: lkmrus/go-education:latest

#      - name: Run tests
#        run: |
#            docker run --env DB_DSN=postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable lkmrus/go-education:latest

