name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: go mod tidy
      - name: Lint
        run: go vet ./cmd
  test:
    needs: [lint]
    strategy:
        matrix:
            go-version: [3.0.0, 3.4.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install deps
        run: go mod tidy
      - name: Test
        run: go test -v ./cmd