name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: go mod tidy
      - name: Lint
        run: go vet ./cmd
  test:
    needs: [lint]
    strategy:
        matrix:
            go-version:
              - 1.20.x
              - 1.19.x
              - 1.18.x
              - stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install deps
        run: go mod tidy
      - name: Test
        run: go test -v ./cmd